extends Node
## Autoload. Sound effects from a small player pool, and music: the title
## loop, the battle loop, and a frame-drum layer that fades in over the
## battle loop during the enemy phase. The drum loop is exactly one bar and
## the battle loop exactly eight, so started together they stay in step.
## All audio is generated by tools/make_audio.py.

const SFX := [
	"cursor", "select", "confirm", "cancel", "menu", "hit", "crit", "miss", "heal",
	"cut", "turn", "measure", "unravel", "fortune", "phase_player", "phase_enemy",
	"victory", "defeat", "death",
]
const SILENT_DB := -60.0

## Linear volumes, 0..1. Set from the settings screen.
var sfx_volume := 0.8
var music_volume := 0.55

var _streams := {}
var _pool: Array[AudioStreamPlayer] = []
var _next := 0
var _music: AudioStreamPlayer
var _drums: AudioStreamPlayer
var _track := ""
var _drums_on := false
var _last_cursor := 0
## Headless runs (tests, smoke) use a dummy audio driver that never reaps
## finished playbacks, so they'd be reported as leaks at exit. Stay silent.
var _silent := false


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_silent = DisplayServer.get_name() == "headless"
	for n in SFX:
		var path := "res://assets/audio/%s.wav" % n
		if ResourceLoader.exists(path):
			_streams[n] = load(path)
	for i in 10:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_pool.append(p)
	_music = AudioStreamPlayer.new()
	_drums = AudioStreamPlayer.new()
	add_child(_music)
	add_child(_drums)


func play(sfx_name: String, pitch: float = 1.0, gain_db: float = 0.0) -> void:
	if _silent or not _streams.has(sfx_name) or sfx_volume <= 0.001:
		return
	if sfx_name == "cursor":
		var now := Time.get_ticks_msec()
		if now - _last_cursor < 45:
			return
		_last_cursor = now
	var p := _pool[_next]
	_next = (_next + 1) % _pool.size()
	p.stream = _streams[sfx_name]
	p.pitch_scale = pitch
	p.volume_db = linear_to_db(sfx_volume) + gain_db
	p.play()


func music(track: String) -> void:
	if track == _track or _silent:
		return
	_track = track
	var stream: AudioStream = null
	if track != "":
		stream = _loop(load("res://assets/audio/music_%s.wav" % track))
	var tw := create_tween()
	if _music.playing:
		tw.tween_property(_music, "volume_db", SILENT_DB, 0.6)
	tw.tween_callback(func() -> void:
		_music.stop()
		_drums.stop()
		if stream == null:
			return
		_music.stream = stream
		_music.volume_db = SILENT_DB
		_music.play()
		if track == "battle":
			_drums.stream = _loop(load("res://assets/audio/music_drums.wav"))
			_drums.volume_db = SILENT_DB
			_drums.play()
		create_tween().tween_property(_music, "volume_db", _music_db(), 1.0))
	_drums_on = false


## Fade the enemy-phase drums in or out.
func drums(on: bool) -> void:
	if on == _drums_on or _track != "battle":
		return
	_drums_on = on
	create_tween().tween_property(_drums, "volume_db", _music_db() - 2.0 if on else SILENT_DB, 0.8)


func apply_volumes() -> void:
	if _music.playing:
		_music.volume_db = _music_db()
	if _drums.playing and _drums_on:
		_drums.volume_db = _music_db() - 2.0


## Stop everything and drop the streams, so a quitting tool leaves nothing
## playing for the engine to report as leaked.
func shutdown() -> void:
	for p in _pool + [_music, _drums]:
		p.stop()
		p.stream = null
	_streams.clear()
	_track = ""


func _music_db() -> float:
	return linear_to_db(maxf(music_volume, 0.0001))


static func _loop(s: AudioStream) -> AudioStream:
	var wav := s as AudioStreamWAV
	if wav != null and wav.loop_mode == AudioStreamWAV.LOOP_DISABLED:
		wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
		wav.loop_begin = 0
		wav.loop_end = int(round(wav.get_length() * wav.mix_rate))
	return s
